<?php

/**
 * Role -> permission matrix, mirrors docs/Doc1-Analisis_Sistem_jstock.md
 * section 3.3 (Matriks Permission RBAC).
 */
return [
    'owner' => [
        'tenant.view', 'tenant.update',
        'users.view', 'users.create', 'users.update', 'users.delete',
        'billing.view', 'billing.manage',
        'clients.view', 'clients.create', 'clients.update', 'clients.delete',
        'products.view', 'products.create', 'products.update', 'products.delete',
        'product-series.view', 'product-series.create', 'product-series.update', 'product-series.delete',
        'transactions.view', 'transactions.create', 'transactions.update', 'transactions.delete', 'transactions.approve',
        'invoices.view', 'invoices.create', 'invoices.update', 'invoices.delete', 'invoices.download',
        'signatures.view', 'signatures.create', 'signatures.update', 'signatures.delete',
        'reports.view', 'reports.cogs',
        'dashboard.view',
        'warehouse-dashboard.view',
        'warehouse-locations.view', 'warehouse-locations.create', 'warehouse-locations.update', 'warehouse-locations.delete',
        'warehouse-items.view', 'warehouse-items.create', 'warehouse-items.update', 'warehouse-items.delete',
        'warehouse-stock.view', 'warehouse-stock.move', 'warehouse-stock.opname',
        'warehouse-suppliers.view', 'warehouse-suppliers.create', 'warehouse-suppliers.update', 'warehouse-suppliers.delete',
        'warehouse-purchase-orders.view', 'warehouse-purchase-orders.create', 'warehouse-purchase-orders.receive',
    ],
    'manager' => [
        'tenant.view',
        'users.view',
        'billing.view',
        'clients.view', 'clients.create', 'clients.update', 'clients.delete',
        'products.view', 'products.create', 'products.update', 'products.delete',
        'product-series.view', 'product-series.create', 'product-series.update', 'product-series.delete',
        'transactions.view', 'transactions.create', 'transactions.update', 'transactions.delete', 'transactions.approve',
        'invoices.view', 'invoices.create', 'invoices.download',
        'signatures.view',
        'reports.view', 'reports.cogs',
        'dashboard.view',
        'warehouse-dashboard.view',
        'warehouse-locations.view', 'warehouse-locations.create', 'warehouse-locations.update', 'warehouse-locations.delete',
        'warehouse-items.view', 'warehouse-items.create', 'warehouse-items.update', 'warehouse-items.delete',
        'warehouse-stock.view', 'warehouse-stock.move', 'warehouse-stock.opname',
        'warehouse-suppliers.view', 'warehouse-suppliers.create', 'warehouse-suppliers.update', 'warehouse-suppliers.delete',
        'warehouse-purchase-orders.view', 'warehouse-purchase-orders.create', 'warehouse-purchase-orders.receive',
    ],
    'operator' => [
        'clients.view', 'clients.create',
        'products.view', 'products.create',
        'product-series.view', 'product-series.create',
        'transactions.view', 'transactions.create',
        'invoices.download',
        'reports.view',
        'dashboard.view',
        'warehouse-dashboard.view',
        'warehouse-locations.view',
        'warehouse-items.view', 'warehouse-items.create',
        'warehouse-stock.view', 'warehouse-stock.move',
        'warehouse-suppliers.view',
        'warehouse-purchase-orders.view', 'warehouse-purchase-orders.create',
    ],
    'viewer' => [
        'clients.view',
        'products.view',
        'product-series.view',
        'transactions.view',
        'invoices.download',
        'reports.view',
        'dashboard.view',
        'warehouse-dashboard.view',
        'warehouse-locations.view',
        'warehouse-items.view',
        'warehouse-stock.view',
        'warehouse-suppliers.view',
        'warehouse-purchase-orders.view',
    ],
    // Super admin operates at platform level, not tenant level — the
    // wildcard is resolved by User::hasPermission().
    'super_admin' => ['*'],
];
